version: "1" 
services:
  # Container NGINX
  nginx:
    image: nginx
    volumes:
      - .:/var/www/docker-laravel/laravel/sites/default.conf /etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php

  # Container PHP
  php:
    image: php:7.2-fpm
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=toor
  
  # Container MYSQL
  mysql:
    image: mysql:8.0.13
    volumes:
       - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=toor

volumes:
  database: